// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA35lbKPh-YjL9HsNIUqUD2Niyf36royIk',
    appId: '1:533597339715:web:b1e912cc5083d7e2e4d4f6',
    messagingSenderId: '533597339715',
    projectId: 'tiktok-75b35',
    authDomain: 'tiktok-75b35.firebaseapp.com',
    storageBucket: 'tiktok-75b35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwTdp1IB92RT-BBRBMQI6yJmkiOebre6o',
    appId: '1:533597339715:android:0a454affd0bc545be4d4f6',
    messagingSenderId: '533597339715',
    projectId: 'tiktok-75b35',
    storageBucket: 'tiktok-75b35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj0-DUHa__QJ8ImiSqdiHokT0GFhKpUmk',
    appId: '1:533597339715:ios:401becded01989d9e4d4f6',
    messagingSenderId: '533597339715',
    projectId: 'tiktok-75b35',
    storageBucket: 'tiktok-75b35.appspot.com',
    iosClientId: '533597339715-mdbll8tg4f7mjnndra79i32femcjav6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj0-DUHa__QJ8ImiSqdiHokT0GFhKpUmk',
    appId: '1:533597339715:ios:401becded01989d9e4d4f6',
    messagingSenderId: '533597339715',
    projectId: 'tiktok-75b35',
    storageBucket: 'tiktok-75b35.appspot.com',
    iosClientId: '533597339715-mdbll8tg4f7mjnndra79i32femcjav6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokfinal',
  );
}
